<?php
declare(strict_types=1);

/**
 * Build the React application, inline all its assets into the HTML,
 * assemble the PHP fragments from src/ around the inlined bundle,
 * and write the result to dist/.
 *
 * Usage:
 *
 *   php build.php                dev build   -> dist/index.php (incl. dev.php)
 *   php build.php release        release     -> dist/sifpress.php (no dev.php)
 *
 * The dev build embeds src/dev.php (?p=dev&action=initData, an
 * admin-gated demo-data seeder). The release build excludes the dev
 * fragment entirely and strips its dispatch from router.php, so the
 * artifact contains no trace of the dev endpoint.
 *
 * The generated file can be copied to:
 *
 *   /
 *   /myapp/
 *   /tools/myapp/
 *
 * without rebuilding and WITHOUT any rewrite rules (.htaccess / Nginx
 * try_files / etc.). All JavaScript and CSS is inlined, so the browser
 * makes exactly one request.
 *
 * Source layout:
 *
 *   src/bootstrap.php    constants + core helpers
 *   src/db.php           SQLite open, pragmas, migration detection/runner, seeds
 *   src/migration.php    ?p=migration handler
 *   src/auth.php         sessions, RBAC, page grants
 *   src/update.php       ?p=update version check / upgrade handler
 *   src/demo_page.php    shared markdown-demo page (virtual + dev seed)
 *   src/api.php          JSON API handler
 *   src/asset.php        binary asset/avatar/blob serving
 *   src/seo.php          settings store + sitemap/robots + head meta injection
 *   src/spa.php          SPA serving / meta injection
 *   src/embed.php        EMBEDDED_HTML region (regenerated by this build)
 *   src/migrations.php   MIGRATIONS region (SQL scripts embedded by this build)
 *   src/dev.php          dev-only ?p=dev handler (dev builds only)
 *   src/router.php       main router
 *
 * The frontend uses pnpm (see frontend/package.json).
 */

$root = __DIR__;
$frontend = $root . '/frontend';
$frontendDist = $frontend . '/dist';
$src = $root . '/src';
$outputDir = $root . '/dist';

$mode = $argv[1] ?? 'dev';

if ($mode === 'release' || $mode === 'rel') {
    $isRelease = true;
} else {
    $isRelease = false;
    $mode = 'dev';
}

$output = $outputDir . ($isRelease ? '/sifpress.php' : '/index.php');

/**
 * Assembly order of the src/ fragments. dev.php is dev-only and
 * must sit before router.php, which dispatches to handle_dev().
 */
$parts = [
    'bootstrap.php',
    'db.php',
    'migration.php',
    'auth.php',
    'update.php',
    'demo_page.php',
    'api.php',
    'asset.php',
    'seo.php',
    'tracking.php',
    'favicon.php',
    'spa.php',
    'embed.php',
    'migrations.php',
];

if (!$isRelease) {
    $parts[] = 'dev.php';
}

$parts[] = 'router.php';

function run(string $command, string $cwd): void
{
    echo '$ ' . $command . PHP_EOL;

    $descriptor = [
        0 => ['pipe', 'r'],
        1 => ['pipe', 'w'],
        2 => ['pipe', 'w'],
    ];

    $process = proc_open($command, $descriptor, $pipes, $cwd);

    if (!is_resource($process)) {
        throw new RuntimeException("Could not execute: $command");
    }

    fclose($pipes[0]);

    $stdout = stream_get_contents($pipes[1]);
    $stderr = stream_get_contents($pipes[2]);

    fclose($pipes[1]);
    fclose($pipes[2]);

    $exitCode = proc_close($process);

    echo $stdout;

    if ($stderr !== '') {
        fwrite(STDERR, $stderr);
    }

    if ($exitCode !== 0) {
        throw new RuntimeException(
            "Command failed with exit code $exitCode: $command"
        );
    }
}

/**
 * Inline every stylesheet and script that references a built asset
 * in dist/. The result is a fully self-contained HTML document.
 */
function inline_assets(string $html, string $dist, bool $dev): string
{
    $html = preg_replace_callback(
        '/<link\b[^>]*\bhref="([^"]+)"[^>]*>/i',
        function (array $match) use ($dist): string {
            $tag = $match[0];
            $href = $match[1];

            // Only inline stylesheets that point into dist/assets/.
            if (!str_contains($tag, 'stylesheet') || !str_contains($href, 'assets/')) {
                return $tag;
            }

            $file = $dist . '/' . ltrim(html_entity_decode($href), './');

            if (!is_file($file)) {
                return $tag;
            }

            $css = file_get_contents($file);

            if ($css === false) {
                return $tag;
            }

            /*
             * Inline any font/asset referenced via url() so the
             * artifact stays fully self-contained (fonts are emitted
             * as separate files by Vite and cannot be fetched after
             * the HTML is inlined into a single PHP file).
             */
            $css = preg_replace_callback(
                '/url\(\s*(?:"([^"]+)"|\'([^\']+)\'|([^)\s]*?))\s*\)/i',
                function (array $m) use ($dist, $file): string {
                    $url = $m[1] !== '' ? $m[1] : ($m[2] !== '' ? $m[2] : trim($m[3]));

                    if ($url === '' || str_starts_with($url, 'data:') || str_starts_with($url, 'http')) {
                        return $m[0];
                    }

                    $candidate = null;

                    if (str_starts_with($url, './')) {
                        $candidate = dirname($file) . '/' . substr($url, 2);
                    } elseif (str_starts_with($url, 'assets/')) {
                        $candidate = $dist . '/' . $url;
                    }

                    $candidate = $candidate !== null ? realpath($candidate) : false;

                    if ($candidate === false || !is_file($candidate)) {
                        return $m[0];
                    }

                    $mime = match (pathinfo($candidate, PATHINFO_EXTENSION)) {
                        'woff2' => 'font/woff2',
                        'woff' => 'font/woff',
                        'ttf' => 'font/ttf',
                        'otf' => 'font/otf',
                        'eot' => 'application/vnd.ms-fontobject',
                        'svg' => 'image/svg+xml',
                        'png' => 'image/png',
                        'jpg', 'jpeg' => 'image/jpeg',
                        'gif' => 'image/gif',
                        'webp' => 'image/webp',
                        default => 'application/octet-stream',
                    };

                    $data = file_get_contents($candidate);

                    if ($data === false) {
                        return $m[0];
                    }

                    return 'url("data:' . $mime . ';base64,' . base64_encode($data) . '")';
                },
                $css
            );

            if ($css === null) {
                return $tag;
            }

            return '<style>' . $css . '</style>';
        },
        $html
    );

    if ($html === null) {
        throw new RuntimeException('Could not inline stylesheets');
    }

    $html = preg_replace_callback(
        '/<script\b[^>]*\bsrc="([^"]+)"[^>]*>/i',
        function (array $match) use ($dist, $dev): string {
            $tag = $match[0];
            $src = $match[1];

            // Only inline scripts that point into dist/assets/.
            if (!str_contains($src, 'assets/')) {
                return $tag;
            }

            $file = $dist . '/' . ltrim(html_entity_decode($src), './');

            if (!is_file($file)) {
                return $tag;
            }

            $js = file_get_contents($file);

            if ($js === false) {
                return $tag;
            }

            // Keep type/crossorigin attributes; drop the src attribute.
            // The opening tag has no closing part, so append the JS and
            // a single closing tag.
            $cleaned = preg_replace('/\bsrc="[^"]*"/i', '', $tag);

            $js = $cleaned . $js . '</script>';

            // Dev builds carry a source map. Embed it as a data URI so the
            // inlined bundle still resolves readable stack traces no matter
            // where the single file is served from.
            if ($dev && preg_match('/\/\/# sourceMappingURL=(index-[A-Za-z0-9_-]+\.js\.map)/', $js, $m)) {
                $map = $dist . '/assets/' . $m[1];
                if (is_file($map)) {
                    $data = file_get_contents($map);
                    if ($data !== false) {
                        $uri = 'data:application/json;charset=utf-8;base64,' . base64_encode($data);
                        $js = str_replace('//# sourceMappingURL=' . $m[1], '//# sourceMappingURL=' . $uri, $js);
                    }
                }
            }

            return $js;
        },
        $html
    );

    if ($html === null) {
        throw new RuntimeException('Could not inline scripts');
    }

    return $html;
}

if (!is_dir($frontend)) {
    throw new RuntimeException('frontend directory not found');
}

if (!is_dir($src)) {
    throw new RuntimeException('src directory not found');
}

foreach ($parts as $part) {
    if (!is_file($src . '/' . $part)) {
        throw new RuntimeException("Missing src fragment: $part");
    }
}

$frontendBuild = $mode === 'release' || $mode === 'rel' ? 'pnpm run build:release' : 'pnpm run build:dev';

if (!is_dir($frontend . '/node_modules')) {
    run('pnpm install', $frontend);
}

run($frontendBuild, $frontend);

if (!is_dir($frontendDist)) {
    throw new RuntimeException('Vite dist directory was not generated');
}

$html = file_get_contents($frontendDist . '/index.html');

if ($html === false) {
    throw new RuntimeException('Could not read frontend/dist/index.html');
}

/*
 * Normalize Vite's relative ./assets/... references. Inlining below
 * only matches assets/..., so "./assets/foo.js" matches too, but keep
 * the HTML tidy by canonicalizing the prefix.
 */
$html = preg_replace(
    '#(?:\./)?assets/#',
    'assets/',
    $html
);

if ($html === null) {
    throw new RuntimeException('Could not normalize asset URLs');
}

/*
 * Inline all JS and CSS so the document is fully self-contained.
 * The static title is stripped; PHP injects a route-aware title.
 * Limit=1: only the single <head> title is a match target — the inlined
 * JS can legitimately contain "<title" (e.g. the commonmark image input
 * rule's `(?<title>…)` group) with no closing tag, which would otherwise
 * make the regex scan the whole bundle and hit the PCRE backtrack limit.
 */
$html = inline_assets($html, $frontendDist, $mode === 'release' || $mode === 'rel' ? false : true);
$html = preg_replace('/<title[^>]*>.*?<\/title>/is', '', $html, 1);

if ($html === null) {
    throw new RuntimeException('Could not strip the static title');
}

/*
 * The HTML is injected into the PHP source as a single-quoted
 * PHP string via var_export(), so arbitrary HTML is safe here.
 */
$htmlPhp = var_export($html, true);

/*
 * Read migrations/*.sql and embed them as a PHP array constant. The
 * SQL scripts are the authoring source of truth; the embedded region
 * makes the single-file artifact self-contained at runtime. Keys are
 * sorted by filename, so db_migrate() applies them in order.
 */
$migrationsDir = $root . '/migrations';

if (!is_dir($migrationsDir)) {
    throw new RuntimeException('migrations directory not found');
}

$migrationFiles = glob($migrationsDir . '/*.sql');

if ($migrationFiles === false || $migrationFiles === []) {
    throw new RuntimeException('No migration files found in migrations/');
}

sort($migrationFiles);
$migrations = [];

foreach ($migrationFiles as $file) {
    $name = basename($file);
    $content = file_get_contents($file);

    if ($content === false) {
        throw new RuntimeException("Could not read migration: $name");
    }

    $migrations[$name] = $content;
}

$migrationsPhp = 'const MIGRATIONS = ' . var_export($migrations, true) . ';';

/*
 * Assemble the single-file artifact from the src/ fragments.
 */
$source = "<?php\ndeclare(strict_types=1);\n\n";

foreach ($parts as $part) {
    $content = file_get_contents($src . '/' . $part);

    if ($content === false) {
        throw new RuntimeException("Could not read src fragment: $part");
    }

    if ($part === 'embed.php') {
        /*
         * Inject the fully inlined HTML into the delimited region.
         * preg_replace_callback returns the literal replacement directly,
         * so unlike a string replacement there is no $/backslash
         * processing. This is also idempotent: it works whether the
         * region currently holds the marker or an earlier build's HTML.
         */
        $count = 0;
        $content = preg_replace_callback(
            '#// ___BEGIN_EMBEDDED___\n.*?// ___END_EMBEDDED___#s',
            function () use ($htmlPhp): string {
                return "// ___BEGIN_EMBEDDED___\nconst EMBEDDED_HTML = " .
                    $htmlPhp . ";\n// ___END_EMBEDDED___";
            },
            $content,
            1,
            $count
        );

        if ($count !== 1) {
            throw new RuntimeException(
                'Could not find the embedded HTML region (matched ' . $count . ')'
            );
        }
    }

    if ($part === 'migrations.php') {
        /*
         * Inject the SQL migrations into the delimited region, the same
         * way the HTML is embedded above.
         */
        $count = 0;
        $content = preg_replace_callback(
            '#// ___BEGIN_MIGRATIONS___\n.*?// ___END_MIGRATIONS___#s',
            function () use ($migrationsPhp): string {
                return "// ___BEGIN_MIGRATIONS___\n" .
                    $migrationsPhp . "\n// ___END_MIGRATIONS___";
            },
            $content,
            1,
            $count
        );

        if ($count !== 1) {
            throw new RuntimeException(
                'Could not find the embedded migrations region (matched ' . $count . ')'
            );
        }
    }

    if ($part === 'router.php' && $isRelease) {
        /*
         * Release builds must not contain any trace of the dev-only
         * module, so strip the dispatch region from router.php.
         */
        $count = 0;
        $content = preg_replace(
            '#\n?// ___BEGIN_DEV_ROUTE___\n.*?// ___END_DEV_ROUTE___\n?#s',
            '',
            $content,
            1,
            $count
        );

        if ($count !== 1) {
            throw new RuntimeException(
                'Could not strip the dev route region (matched ' . $count . ')'
            );
        }
    }

    $source .= $content . PHP_EOL;
}

if (!is_dir($outputDir)) {
    mkdir($outputDir, 0777, true);
}

$tmp = $outputDir . '/.index.php.tmp';

if (file_put_contents($tmp, $source) === false) {
    throw new RuntimeException('Could not write ' . $tmp);
}

if (!rename($tmp, $output)) {
    unlink($tmp);
    throw new RuntimeException('Could not write ' . $output);
}

echo PHP_EOL;
echo "Build complete." . PHP_EOL;
echo "Artifact: " . ($isRelease ? 'dist/sifpress.php (release, no dev.php)' : 'dist/index.php (dev, dev.php included)') . PHP_EOL;
echo PHP_EOL;
echo "No .htaccess, no rewrite rules are required." . PHP_EOL;
echo "Routes: /index.php?p=/...   API: /index.php?p=api&action=..." . PHP_EOL;
