<?php
declare(strict_types=1);

/**
 * Build the React application, inline all its assets into the HTML,
 * assemble the PHP fragments from src/ around the inlined bundle,
 * and write the result to dist/index.php.
 *
 * Usage:
 *
 *   php build.php
 *
 * Production artifact:
 *
 *   dist/index.php
 *
 * The generated file can be copied to:
 *
 *   /
 *   /myapp/
 *   /tools/myapp/
 *
 * without rebuilding and WITHOUT any rewrite rules (.htaccess / Nginx
 * try_files / etc.). All JavaScript and CSS is inlined, so the browser
 * makes exactly one request.
 *
 * Source layout:
 *
 *   src/bootstrap.php   constants + core helpers
 *   src/api.php         JSON API handler
 *   src/spa.php         SPA serving / meta injection
 *   src/embed.php       EMBEDDED_HTML region (regenerated by this build)
 *   src/router.php      main router
 *
 * The frontend uses pnpm (see frontend/package.json).
 */

$root = __DIR__;
$frontend = $root . '/frontend';
$frontendDist = $frontend . '/dist';
$src = $root . '/src';
$outputDir = $root . '/dist';
$output = $outputDir . '/index.php';

/** Assembly order of the src/ fragments. */
$parts = [
    'bootstrap.php',
    'api.php',
    'spa.php',
    'embed.php',
    'router.php',
];

function run(string $command, string $cwd): void
{
    echo '$ ' . $command . PHP_EOL;

    $descriptor = [
        0 => ['pipe', 'r'],
        1 => ['pipe', 'w'],
        2 => ['pipe', 'w'],
    ];

    $process = proc_open($command, $descriptor, $pipes, $cwd);

    if (!is_resource($process)) {
        throw new RuntimeException("Could not execute: $command");
    }

    fclose($pipes[0]);

    $stdout = stream_get_contents($pipes[1]);
    $stderr = stream_get_contents($pipes[2]);

    fclose($pipes[1]);
    fclose($pipes[2]);

    $exitCode = proc_close($process);

    echo $stdout;

    if ($stderr !== '') {
        fwrite(STDERR, $stderr);
    }

    if ($exitCode !== 0) {
        throw new RuntimeException(
            "Command failed with exit code $exitCode: $command"
        );
    }
}

/**
 * Inline every stylesheet and script that references a built asset
 * in dist/. The result is a fully self-contained HTML document.
 */
function inline_assets(string $html, string $dist): string
{
    $html = preg_replace_callback(
        '/<link\b[^>]*\bhref="([^"]+)"[^>]*>/i',
        function (array $match) use ($dist): string {
            $tag = $match[0];
            $href = $match[1];

            // Only inline stylesheets that point into dist/assets/.
            if (!str_contains($tag, 'stylesheet') || !str_contains($href, 'assets/')) {
                return $tag;
            }

            $file = $dist . '/' . ltrim(html_entity_decode($href), './');

            if (!is_file($file)) {
                return $tag;
            }

            $css = file_get_contents($file);

            if ($css === false) {
                return $tag;
            }

            return '<style>' . $css . '</style>';
        },
        $html
    );

    if ($html === null) {
        throw new RuntimeException('Could not inline stylesheets');
    }

    $html = preg_replace_callback(
        '/<script\b[^>]*\bsrc="([^"]+)"[^>]*>/i',
        function (array $match) use ($dist): string {
            $tag = $match[0];
            $src = $match[1];

            // Only inline scripts that point into dist/assets/.
            if (!str_contains($src, 'assets/')) {
                return $tag;
            }

            $file = $dist . '/' . ltrim(html_entity_decode($src), './');

            if (!is_file($file)) {
                return $tag;
            }

            $js = file_get_contents($file);

            if ($js === false) {
                return $tag;
            }

            // Keep type/crossorigin attributes; drop the src attribute.
            // The opening tag has no closing part, so append the JS and
            // a single closing tag.
            $cleaned = preg_replace('/\bsrc="[^"]*"/i', '', $tag);

            return $cleaned . $js . '</script>';
        },
        $html
    );

    if ($html === null) {
        throw new RuntimeException('Could not inline scripts');
    }

    return $html;
}

if (!is_dir($frontend)) {
    throw new RuntimeException('frontend directory not found');
}

if (!is_dir($src)) {
    throw new RuntimeException('src directory not found');
}

foreach ($parts as $part) {
    if (!is_file($src . '/' . $part)) {
        throw new RuntimeException("Missing src fragment: $part");
    }
}

if (!is_dir($frontend . '/node_modules')) {
    run('pnpm install', $frontend);
}

run('pnpm run build', $frontend);

if (!is_dir($frontendDist)) {
    throw new RuntimeException('Vite dist directory was not generated');
}

$html = file_get_contents($frontendDist . '/index.html');

if ($html === false) {
    throw new RuntimeException('Could not read frontend/dist/index.html');
}

/*
 * Normalize Vite's relative ./assets/... references. Inlining below
 * only matches assets/..., so "./assets/foo.js" matches too, but keep
 * the HTML tidy by canonicalizing the prefix.
 */
$html = preg_replace(
    '#(?:\./)?assets/#',
    'assets/',
    $html
);

if ($html === null) {
    throw new RuntimeException('Could not normalize asset URLs');
}

/*
 * Inline all JS and CSS so the document is fully self-contained.
 * The static title is stripped; PHP injects a route-aware title.
 */
$html = inline_assets($html, $frontendDist);
$html = preg_replace('/<title[^>]*>.*?<\/title>/is', '', $html);

if ($html === null) {
    throw new RuntimeException('Could not strip the static title');
}

/*
 * The HTML is injected into the PHP source as a single-quoted
 * PHP string via var_export(), so arbitrary HTML is safe here.
 */
$htmlPhp = var_export($html, true);

/*
 * Assemble the single-file artifact from the src/ fragments.
 */
$source = "<?php\ndeclare(strict_types=1);\n\n";

foreach ($parts as $part) {
    $content = file_get_contents($src . '/' . $part);

    if ($content === false) {
        throw new RuntimeException("Could not read src fragment: $part");
    }

    if ($part === 'embed.php') {
        /*
         * Inject the fully inlined HTML into the delimited region.
         * preg_replace_callback returns the literal replacement directly,
         * so unlike a string replacement there is no $/backslash
         * processing. This is also idempotent: it works whether the
         * region currently holds the marker or an earlier build's HTML.
         */
        $count = 0;
        $content = preg_replace_callback(
            '#// ___BEGIN_EMBEDDED___\n.*?// ___END_EMBEDDED___#s',
            function () use ($htmlPhp): string {
                return "// ___BEGIN_EMBEDDED___\nconst EMBEDDED_HTML = " .
                    $htmlPhp . ";\n// ___END_EMBEDDED___";
            },
            $content,
            1,
            $count
        );

        if ($count !== 1) {
            throw new RuntimeException(
                'Could not find the embedded HTML region (matched ' . $count . ')'
            );
        }
    }

    $source .= $content . PHP_EOL;
}

if (!is_dir($outputDir)) {
    mkdir($outputDir, 0777, true);
}

$tmp = $outputDir . '/.index.php.tmp';

if (file_put_contents($tmp, $source) === false) {
    throw new RuntimeException('Could not write ' . $tmp);
}

if (!rename($tmp, $output)) {
    unlink($tmp);
    throw new RuntimeException('Could not write ' . $output);
}

echo PHP_EOL;
echo "Build complete." . PHP_EOL;
echo "Production artifact: dist/index.php" . PHP_EOL;
echo PHP_EOL;
echo "No .htaccess, no rewrite rules are required." . PHP_EOL;
echo "Routes: /index.php?u=...   API: /index.php?module=api&action=..." . PHP_EOL;
