<?php
declare(strict_types=1);

/**
 * Build every sifront SPA (each a pnpm workspace package under sifronts/)
 * into a ZIP bundle: dist/<name>.sifront.
 *
 * The bundle has exactly two entries:
 *   meta.json   identity + version + theme keys (require_keys, …)
 *   bundle.js   the raw app bundle with its CSS/fonts inlined
 *
 * Usage:
 *
 *   php buildfront.php          dev bundle    (unminified + embedded sourcemap)
 *   php buildfront.php release  release bundle (minified)
 *
 * Shares the build/inlining helpers with build.php (build_common.php).
 * This script does NOT touch the PHP artifact (dist/index.php /
 * dist/sifpress.php) — use build.php for that.
 *
 * A sifront is served inside a small HTML shell generated by the backend
 * (see src/spa.php), which supplies the theme bootstrap and the shared
 * ui-sdk module; the ZIP itself carries no HTML.
 */

$root = __DIR__;
$outputDir = $root . '/dist';

$mode = $argv[1] ?? 'dev';

if ($mode === 'release' || $mode === 'rel') {
    $isRelease = true;
} else {
    $isRelease = false;
    $mode = 'dev';
}

$buildCommand = $isRelease ? 'pnpm run build:release' : 'pnpm run build:dev';

require __DIR__ . '/build_common.php';

/**
 * Build one sifront SPA and package its Vite output into a two-entry ZIP
 * (`meta.json` + `bundle.js`) written to <outputDir>/<name>.sifront.
 */
function build_sifront(string $appDir, string $outputDir, string $buildCommand, bool $dev): void
{
    $name = basename($appDir);
    $dist = $appDir . '/dist';

    if (!is_dir($appDir . '/node_modules')) {
        run('pnpm install', $appDir);
    }

    run($buildCommand, $appDir);

    $html = file_get_contents($dist . '/index.html');

    if ($html === false) {
        throw new RuntimeException("Could not read $name/dist/index.html");
    }

    /*
     * Locate the Vite app bundle + stylesheet. The ZIP carries JS and CSS
     * as a single `bundle.js`: the stylesheet is prepended as a tiny runtime
     * injector and its fonts are inlined as data: URIs so the file stays
     * self-contained.
     */
    if (preg_match('#<script[^>]*\bsrc="((?:\./)?assets/[^"]+\.js)"#i', $html, $jsMatch) !== 1) {
        throw new RuntimeException("No app bundle found in $name/dist/index.html");
    }

    $jsFile = $dist . '/' . ltrim(html_entity_decode($jsMatch[1]), './');
    $js = file_get_contents($jsFile);

    if ($js === false) {
        throw new RuntimeException("Could not read $jsFile");
    }

    $css = '';

    if (preg_match('#<link[^>]*\bhref="((?:\./)?assets/[^"]+\.css)"#i', $html, $cssMatch) === 1) {
        $cssFile = $dist . '/' . ltrim(html_entity_decode($cssMatch[1]), './');
        $rawCss = file_get_contents($cssFile);

        if ($rawCss === false) {
            throw new RuntimeException("Could not read $cssFile");
        }

        $css = inline_css_urls($rawCss, $dist, $cssFile);
    }

    /*
     * Dev bundles carry a source map: embed it as a data URI so the ZIP
     * still has exactly two entries while stack traces stay readable.
     */
    if ($dev && preg_match('/\/\/# sourceMappingURL=(index-[A-Za-z0-9_-]+\.js\.map)/', $js, $mapMatch) === 1) {
        $mapFile = $dist . '/assets/' . $mapMatch[1];

        if (is_file($mapFile)) {
            $mapData = file_get_contents($mapFile);

            if ($mapData !== false) {
                $uri = 'data:application/json;charset=utf-8;base64,' . base64_encode($mapData);
                $js = str_replace('//# sourceMappingURL=' . $mapMatch[1], '//# sourceMappingURL=' . $uri, $js);
            }
        }
    }

    $cssLiteral = json_encode(
        $css,
        JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
            | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT
    );

    if ($cssLiteral === false) {
        throw new RuntimeException("Could not encode the $name stylesheet");
    }

    $bundle = '(function(){var s=document.createElement("style");'
        . 's.setAttribute("data-sifront","' . $name . '");s.textContent='
        . $cssLiteral . ';document.head.appendChild(s);})();'
        . "\n" . $js;

    /*
     * meta.json is the sifront's identity + theme contract. Author keys
     * (require_keys, …) are kept; identity fields are injected from
     * package.json / the build environment.
     */
    $meta = [];
    $metaFile = $appDir . '/meta.json';

    if (is_file($metaFile)) {
        $decoded = json_decode((string) file_get_contents($metaFile), true);

        if (!is_array($decoded)) {
            throw new RuntimeException("Invalid JSON in $metaFile");
        }

        $meta = $decoded;
    }

    $pkgFile = $appDir . '/package.json';
    $pkg = is_file($pkgFile) ? json_decode((string) file_get_contents($pkgFile), true) : null;
    $version = is_array($pkg) && is_string($pkg['version'] ?? null) ? $pkg['version'] : '0.0.0';

    $title = '';

    if (is_string($meta['title'] ?? null) && $meta['title'] !== '') {
        $title = $meta['title'];
    } elseif (preg_match('#<title>([^<]*)</title>#i', $html, $titleMatch) === 1) {
        $title = trim($titleMatch[1]);
    }

    $meta = array_merge($meta, [
        'schema' => 1,
        'name' => $name,
        'title' => $title !== '' ? $title : $name,
        'version' => $version,
        'built_at' => gmdate('c'),
        'entry' => 'bundle.js',
    ]);

    $metaJson = json_encode(
        $meta,
        JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT
    );

    if ($metaJson === false) {
        throw new RuntimeException("Could not encode meta for $name");
    }

    $output = $outputDir . '/' . $name . '.sifront';

    zip_create($output, [
        'meta.json' => $metaJson,
        'bundle.js' => $bundle,
    ]);

    /*
     * Dev-serving companions: the backend reads these plain files (never the
     * ZIP), so the in-repo `sifpress1` can be iterated on without a re-upload.
     */
    file_put_contents($outputDir . '/' . $name . '.meta.json', $metaJson);
    file_put_contents($outputDir . '/' . $name . '.bundle.js', $bundle);

    echo "Sifront bundle: $output (v$version)" . PHP_EOL;
}

$sifrontApps = glob($root . '/sifronts/*', GLOB_ONLYDIR);

if ($sifrontApps === false || $sifrontApps === []) {
    throw new RuntimeException('No sifront packages found under sifronts/');
}

foreach ($sifrontApps as $sifrontApp) {
    if (!is_file($sifrontApp . '/package.json')) {
        continue;
    }

    build_sifront($sifrontApp, $outputDir, $buildCommand, !$isRelease);
}

echo PHP_EOL;
echo 'Build complete.' . PHP_EOL;
echo 'Mode: ' . $mode . PHP_EOL;
echo PHP_EOL;
echo 'Bundles are ZIP archives (meta.json + bundle.js), ready to be stored/served as a sifront.' . PHP_EOL;
