/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as SectionSectionRouteImport } from './routes/section.$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionSectionRoute = SectionSectionRouteImport.update({
  id: '/section/$section',
  path: '/section/$section',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/archive': typeof ArchiveRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/section/$section': typeof SectionSectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/archive': typeof ArchiveRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/section/$section': typeof SectionSectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/archive': typeof ArchiveRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/section/$section': typeof SectionSectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/archive' | '/article/$slug' | '/section/$section'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/archive' | '/article/$slug' | '/section/$section'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/archive'
    | '/article/$slug'
    | '/section/$section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ArchiveRoute: typeof ArchiveRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  SectionSectionRoute: typeof SectionSectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section/$section': {
      id: '/section/$section'
      path: '/section/$section'
      fullPath: '/section/$section'
      preLoaderRoute: typeof SectionSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ArchiveRoute: ArchiveRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  SectionSectionRoute: SectionSectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
