/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAccountRouteImport } from './routes/admin/account'
import { Route as AdminAccountAdminRouteImport } from './routes/admin/account-admin'
import { Route as AdminArticlesRouteImport } from './routes/admin/articles'
import { Route as AdminAssetsRouteImport } from './routes/admin/assets'
import { Route as AdminKvsRouteImport } from './routes/admin/kvs'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminArticleSlugRouteImport } from './routes/admin/article.$slug'
import { Route as AdminEditorSlugRouteImport } from './routes/admin/editor/$slug'
import { Route as AdminEditorNewRouteImport } from './routes/admin/editor/new'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/admin/account',
  path: '/admin/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountAdminRoute = AdminAccountAdminRouteImport.update({
  id: '/admin/account-admin',
  path: '/admin/account-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/admin/articles',
  path: '/admin/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssetsRoute = AdminAssetsRouteImport.update({
  id: '/admin/assets',
  path: '/admin/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKvsRoute = AdminKvsRouteImport.update({
  id: '/admin/kvs',
  path: '/admin/kvs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticleSlugRoute = AdminArticleSlugRouteImport.update({
  id: '/admin/article/$slug',
  path: '/admin/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditorSlugRoute = AdminEditorSlugRouteImport.update({
  id: '/admin/editor/$slug',
  path: '/admin/editor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditorNewRoute = AdminEditorNewRouteImport.update({
  id: '/admin/editor/new',
  path: '/admin/editor/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/account-admin': typeof AdminAccountAdminRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/kvs': typeof AdminKvsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/article/$slug': typeof AdminArticleSlugRoute
  '/admin/editor/$slug': typeof AdminEditorSlugRoute
  '/admin/editor/new': typeof AdminEditorNewRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/account-admin': typeof AdminAccountAdminRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/kvs': typeof AdminKvsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/article/$slug': typeof AdminArticleSlugRoute
  '/admin/editor/$slug': typeof AdminEditorSlugRoute
  '/admin/editor/new': typeof AdminEditorNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/account-admin': typeof AdminAccountAdminRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/kvs': typeof AdminKvsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/article/$slug': typeof AdminArticleSlugRoute
  '/admin/editor/$slug': typeof AdminEditorSlugRoute
  '/admin/editor/new': typeof AdminEditorNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/admin/account'
    | '/admin/account-admin'
    | '/admin/articles'
    | '/admin/assets'
    | '/admin/kvs'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/'
    | '/admin/article/$slug'
    | '/admin/editor/$slug'
    | '/admin/editor/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/admin/account'
    | '/admin/account-admin'
    | '/admin/articles'
    | '/admin/assets'
    | '/admin/kvs'
    | '/admin/login'
    | '/admin/settings'
    | '/admin'
    | '/admin/article/$slug'
    | '/admin/editor/$slug'
    | '/admin/editor/new'
  id:
    | '__root__'
    | '/$'
    | '/admin/account'
    | '/admin/account-admin'
    | '/admin/articles'
    | '/admin/assets'
    | '/admin/kvs'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/'
    | '/admin/article/$slug'
    | '/admin/editor/$slug'
    | '/admin/editor/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AdminAccountRoute: typeof AdminAccountRoute
  AdminAccountAdminRoute: typeof AdminAccountAdminRoute
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminAssetsRoute: typeof AdminAssetsRoute
  AdminKvsRoute: typeof AdminKvsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArticleSlugRoute: typeof AdminArticleSlugRoute
  AdminEditorSlugRoute: typeof AdminEditorSlugRoute
  AdminEditorNewRoute: typeof AdminEditorNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/admin/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/account-admin': {
      id: '/admin/account-admin'
      path: '/admin/account-admin'
      fullPath: '/admin/account-admin'
      preLoaderRoute: typeof AdminAccountAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/admin/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assets': {
      id: '/admin/assets'
      path: '/admin/assets'
      fullPath: '/admin/assets'
      preLoaderRoute: typeof AdminAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kvs': {
      id: '/admin/kvs'
      path: '/admin/kvs'
      fullPath: '/admin/kvs'
      preLoaderRoute: typeof AdminKvsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/article/$slug': {
      id: '/admin/article/$slug'
      path: '/admin/article/$slug'
      fullPath: '/admin/article/$slug'
      preLoaderRoute: typeof AdminArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/editor/$slug': {
      id: '/admin/editor/$slug'
      path: '/admin/editor/$slug'
      fullPath: '/admin/editor/$slug'
      preLoaderRoute: typeof AdminEditorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/editor/new': {
      id: '/admin/editor/new'
      path: '/admin/editor/new'
      fullPath: '/admin/editor/new'
      preLoaderRoute: typeof AdminEditorNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AdminAccountRoute: AdminAccountRoute,
  AdminAccountAdminRoute: AdminAccountAdminRoute,
  AdminArticlesRoute: AdminArticlesRoute,
  AdminAssetsRoute: AdminAssetsRoute,
  AdminKvsRoute: AdminKvsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminArticleSlugRoute: AdminArticleSlugRoute,
  AdminEditorSlugRoute: AdminEditorSlugRoute,
  AdminEditorNewRoute: AdminEditorNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
