/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ArticleRouteImport } from './routes/article'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as EditorSlugRouteImport } from './routes/editor/$slug'
import { Route as EditorNewRouteImport } from './routes/editor/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleRoute = ArticleRouteImport.update({
  id: '/article',
  path: '/article',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticleRoute,
} as any)
const EditorSlugRoute = EditorSlugRouteImport.update({
  id: '/editor/$slug',
  path: '/editor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorNewRoute = EditorNewRouteImport.update({
  id: '/editor/new',
  path: '/editor/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/article': typeof ArticleRouteWithChildren
  '/assets': typeof AssetsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/editor/$slug': typeof EditorSlugRoute
  '/editor/new': typeof EditorNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/article': typeof ArticleRouteWithChildren
  '/assets': typeof AssetsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/editor/$slug': typeof EditorSlugRoute
  '/editor/new': typeof EditorNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/article': typeof ArticleRouteWithChildren
  '/assets': typeof AssetsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/editor/$slug': typeof EditorSlugRoute
  '/editor/new': typeof EditorNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/account'
    | '/article'
    | '/assets'
    | '/login'
    | '/settings'
    | '/article/$slug'
    | '/editor/$slug'
    | '/editor/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/account'
    | '/article'
    | '/assets'
    | '/login'
    | '/settings'
    | '/article/$slug'
    | '/editor/$slug'
    | '/editor/new'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/account'
    | '/article'
    | '/assets'
    | '/login'
    | '/settings'
    | '/article/$slug'
    | '/editor/$slug'
    | '/editor/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AccountRoute: typeof AccountRoute
  ArticleRoute: typeof ArticleRouteWithChildren
  AssetsRoute: typeof AssetsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  EditorSlugRoute: typeof EditorSlugRoute
  EditorNewRoute: typeof EditorNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article': {
      id: '/article'
      path: '/article'
      fullPath: '/article'
      preLoaderRoute: typeof ArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof ArticleRoute
    }
    '/editor/$slug': {
      id: '/editor/$slug'
      path: '/editor/$slug'
      fullPath: '/editor/$slug'
      preLoaderRoute: typeof EditorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/new': {
      id: '/editor/new'
      path: '/editor/new'
      fullPath: '/editor/new'
      preLoaderRoute: typeof EditorNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ArticleRouteChildren {
  ArticleSlugRoute: typeof ArticleSlugRoute
}

const ArticleRouteChildren: ArticleRouteChildren = {
  ArticleSlugRoute: ArticleSlugRoute,
}

const ArticleRouteWithChildren =
  ArticleRoute._addFileChildren(ArticleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AccountRoute: AccountRoute,
  ArticleRoute: ArticleRouteWithChildren,
  AssetsRoute: AssetsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  EditorSlugRoute: EditorSlugRoute,
  EditorNewRoute: EditorNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
