/**
 * ------------------------------------------------------------
 * URL modes
 *
 * The artifact routes everything through one query parameter:
 *
 *   /index.php?p=sifpress/admin/assets  -> the admin SPA route /admin/assets
 *   /index.php?p=sifpress/api&action=…  -> the JSON API
 *   /index.php?p=/article/hello-world   -> the sifront route /article/hello-world
 *
 * That form needs no server configuration at all. Installing the rules
 * generated by `php sifpress.php rewrite apache|nginx` additionally lets every
 * route be addressed as a path — /sifpress/admin/assets, /article/hello-world,
 * /robots.txt — by copying the path into ?p=, which is the same dispatch the
 * query form already performs.
 *
 * Both forms are always *accepted*, so old bookmarks, old links in a cached
 * bundle and sifront archives built before this feature keep working. Only the
 * form the app *emits* depends on pretty_urls_enabled():
 *
 *   SIFPRESS_PRETTY_URLS = '1'      force pretty links
 *                     = '0'      force ?p= links
 *                     = 'auto'   (default) pretty only once a pretty request
 *                                has actually been observed, i.e. after the
 *                                rewrite rules are live
 *
 * 'auto' never optimistically turns on: an install whose rules were removed
 * keeps emitting ?p= links instead of links that 404.
 * ------------------------------------------------------------
 */

/** Longest route accepted from a URL path; anything longer is truncated. */
const ROUTE_MAX_LENGTH = 512;

/**
 * URL path the artifact is mounted at: '' for <docroot>/index.php, '/app' for
 * <docroot>/app/index.php.
 *
 * Normal SAPIs (mod_php, php-fpm) report the script in SCRIPT_NAME, so the
 * mount is its directory. The built-in dev server instead reports the
 * *request* there and the script in SCRIPT_FILENAME, so fall back to the gap
 * between DOCUMENT_ROOT and that file. A non-.php script name that is not the
 * document root either yields '' — the conservative answer.
 */
function mount_path(): string
{
    static $mount = null;

    if ($mount !== null) {
        return $mount;
    }

    $mount = '';
    $name = (string) ($_SERVER['SCRIPT_NAME'] ?? '');

    if ($name !== '' && preg_match('/\.php$/i', $name) === 1) {
        $dir = rtrim(str_replace('\\', '/', dirname($name)), '/');

        return $mount = ($dir === '.' || $dir === '') ? '' : $dir;
    }

    $file = str_replace('\\', '/', (string) ($_SERVER['SCRIPT_FILENAME'] ?? ''));
    $root = rtrim(str_replace('\\', '/', (string) ($_SERVER['DOCUMENT_ROOT'] ?? '')), '/');

    if ($file !== '' && $root !== '' && str_starts_with($file, $root . '/')) {
        $dir = rtrim(dirname(substr($file, strlen($root))), '/');

        if ($dir !== '.' && $dir !== '') {
            $mount = $dir;
        }
    }

    return $mount;
}

/**
 * Drop the mount prefix from a path, so a rule that hands the whole request
 * path to ?p= (nginx: `try_files … /app/index.php?p=$uri`) resolves to the
 * same route as one written relative to the mount directory.
 */
function strip_mount_prefix(string $path): string
{
    $mount = mount_path();

    if ($mount !== '' && ($path === $mount || str_starts_with($path, $mount . '/'))) {
        return substr($path, strlen($mount));
    }

    return $path;
}

/**
 * Turn a raw path into a safe route: percent-decoded, `.`/`..`/empty segments
 * collapsed, control characters removed and length-capped. The route is only
 * ever used to pick a handler, but it can now come from a URL path, so it is
 * normalised the same way the query form is.
 */
function normalize_route(string $path): string
{
    if ($path === '') {
        return '';
    }

    $path = str_replace(["\0", "\r", "\n"], ' ', rawurldecode($path));
    $segments = [];

    foreach (explode('/', $path) as $segment) {
        $segment = trim($segment);

        if ($segment === '' || $segment === '.') {
            continue;
        }

        if ($segment === '..') {
            array_pop($segments);
            continue;
        }

        $segments[] = $segment;
    }

    $route = implode('/', $segments);

    if (strlen($route) > ROUTE_MAX_LENGTH) {
        $route = substr($route, 0, ROUTE_MAX_LENGTH);
    }

    return $route;
}

/**
 * Path this request addressed, or '' when it addressed the artifact itself
 * (plain /index.php, /index.php?p=…, which is the rewrite-free form). Falls
 * back to PATH_INFO for server configs that hand the route that way instead
 * (Apache's FallbackResource, a hand-rolled proxy rule).
 */
function request_path(): string
{
    $path = parse_url((string) ($_SERVER['REQUEST_URI'] ?? ''), PHP_URL_PATH);
    $path = is_string($path) ? $path : '';
    $name = (string) ($_SERVER['SCRIPT_NAME'] ?? '');
    $info = (string) ($_SERVER['PATH_INFO'] ?? '');

    /*
     * The artifact URL itself (…/index.php) carries no route. Only a real
     * script name means that: the built-in dev server reports the *request*
     * in SCRIPT_NAME, and that request is the route.
     */
    $isArtifact = $name !== ''
        && preg_match('/\.php$/i', $name) === 1
        && $path === $name;

    if ($path === '' || $isArtifact) {
        $path = $info;
    }

    return strip_mount_prefix($path);
}

/**
 * The route this request addresses: `?p=` when present, otherwise the request
 * path. Both spellings reach the same dispatch.
 */
function request_route(): string
{
    $p = $_GET['p'] ?? null;

    if (is_string($p) && $p !== '') {
        return normalize_route(strip_mount_prefix($p));
    }

    return normalize_route(request_path());
}

/**
 * True when the request arrived on a path rather than on the artifact URL —
 * proof that the rewrite rules are installed. The site root is not a path
 * (nothing was rewritten for it).
 */
function request_is_pretty(): bool
{
    $path = request_path();

    return $path !== '' && $path !== '/';
}

/** Sticky marker written the first time a pretty request is observed. */
function pretty_urls_flag_path(): string
{
    return db_dir() . '/pretty_urls';
}

/**
 * Remember that pretty requests are being served. Silently skipped when the
 * DB folder is not writable — auto mode then simply re-observes the next
 * pretty request.
 */
function remember_pretty_urls(): void
{
    static $done = false;

    if ($done) {
        return;
    }

    $done = true;
    $path = pretty_urls_flag_path();

    if (!is_file($path)) {
        @file_put_contents($path, "1\n");
    }
}

/** Delete the sticky marker (CLI `rewrite --forget`). True when one was there. */
function forget_pretty_urls(): bool
{
    $path = pretty_urls_flag_path();

    return is_file($path) ? @unlink($path) : false;
}

/**
 * Whether links should be emitted in the pretty path form. See the header for
 * the SIFPRESS_PRETTY_URLS precedence.
 */
function pretty_urls_enabled(): bool
{
    static $enabled = null;

    if ($enabled !== null) {
        return $enabled;
    }

    $mode = defined('SIFPRESS_PRETTY_URLS')
        ? strtolower(trim((string) SIFPRESS_PRETTY_URLS))
        : '';

    if ($mode === '') {
        $env = getenv('SIFPRESS_PRETTY_URLS');
        $mode = is_string($env) ? strtolower(trim($env)) : '';
    }

    if (in_array($mode, ['1', 'true', 'on', 'yes'], true)) {
        return $enabled = true;
    }

    if (in_array($mode, ['0', 'false', 'off', 'no'], true)) {
        return $enabled = false;
    }

    if (request_is_pretty()) {
        remember_pretty_urls();

        return $enabled = true;
    }

    return $enabled = is_file(pretty_urls_flag_path());
}

/**
 * URL for a route, relative to the host root, in whichever mode is active.
 *
 *   pretty  /sifpress/asset?id=7        (/app/sifpress/asset?id=7 mounted)
 *   query   ?p=sifpress/asset&id=7     (document-relative, so any mount works)
 *
 * The root route ('/' or '') has no ?p= form — it is the artifact URL itself —
 * so it always renders as the mount path.
 */
function route_path(string $route, array $query = []): string
{
    $route = normalize_route($route);
    $qs = $query === [] ? '' : http_build_query($query);

    if ($route === '') {
        $root = mount_path() . '/';

        return $qs === '' ? $root : $root . '?' . $qs;
    }

    if (pretty_urls_enabled()) {
        return mount_path() . '/' . $route . ($qs === '' ? '' : '?' . $qs);
    }

    return '?p=' . $route . ($qs === '' ? '' : '&' . $qs);
}

/**
 * Absolute URL for a route (canonical links, og:image, sitemap, Location:).
 * In query mode it stays anchored on the artifact URL; in pretty mode it is
 * origin + mount + path, which is exactly what the browser address bar shows.
 */
function route_url(string $route, array $query = []): string
{
    $route = normalize_route($route);

    if (pretty_urls_enabled()) {
        return (canonical_origin() ?? '') . route_path($route, $query);
    }

    if ($route === '') {
        return base_url();
    }

    return base_url() . route_path($route, $query);
}
